### ISSUE TITLE
Bowser Crash on IPAD

### ISSUE THREAD

**Issue by lemos-beta** [EricssonResearch/bowser#49] opened 2015-06-11 13:03 UTC
Bowser crash on IPAD 4 and iOS 8.

**Comment by saghul** [comment] 2015-09-14 14:39
I get the same, crashes every single time, on page load.

**Comment by superdump** [comment] 2015-09-14 20:06
The root cause is here: https://github.com/EricssonResearch/openwebrtc/issues/385 Please follow that issue. Closing this issue.

**Closed by superdump** 2015-09-14 20:06 UTC
