### ISSUE TITLE
Version 0.5 crashes on load

### ISSUE THREAD

**Issue by pachpage** [EricssonResearch/bowser#45] opened 2015-05-21 11:54 UTC
Whether it's opened by tapping the home screen icon or using the "bowser://" URL scheme, the app crashes before finishing initializing.

**Comment by superdump** [comment] 2015-05-21 12:54
What device are you using? It seems to work fine on my iPhone 6 Plus

**Comment by stefhak** [comment] 2015-05-21 13:12
Works on my iPhone 5S as well FWIW.

**Comment by mostafar** [comment] 2015-05-21 15:58
I have the same experience on iPad with iOS 8.1.1

**Comment by superdump** [comment] 2015-05-21 16:26
@mostafar - which iPad?

My suspicion is that older devices struggle to process the language bindings resource-wise. We had added pre-generated language bindings to the app bundle I thought, which should have sped up first start and avoided such problems.

**Comment by mostafar** [comment] 2015-05-21 16:29
iPad (first gen), now after some tries I think it crashes less than a second after initialization is finished, I can see the url in the box for one second.

**Comment by zevarito** [comment] 2015-05-21 16:43
I've noticed that if I type an url (which should redirect to https) without
including https:// I get "Frame error", but if I indeed include https:// in
the url input box it works.

On Thu, May 21, 2015 at 1:29 PM, Mostafa Rokooie <notifications@github.com>
wrote:

> iPad (first gen), now after some tries I think it crashes less than a
> second after initialization is finished, I can see the url in the box for
> one second.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/45#issuecomment-104344768>
> .
>



-- 
Alvaro

**Comment by mostafar** [comment] 2015-05-21 16:55
Thanks @zevarito but, I can not change the url because it crashes on start, and the url is the default url (openwebrtc.io/bowser)!

**Comment by superdump** [comment] 2015-05-21 17:01
A first generation iPad is very likely really going to struggle with real-time audio/video even in optimal circumstances.

In order to add WebRTC support to a UIWebView from outside of the iPhone platform SDK has led us to use a suboptimal rendering method where all video frames are decided to bitmaps which are then displayed by the UIWebView as images, just that the image is updated rapidly. That is, Bowser is not optimal.

You may be able to use the WebRTC data channel though. :)

Regardless, this crash issue is a real issue.

**Comment by mostafar** [comment] 2015-05-21 17:11
Thank you guys for creating the Bowser, Actually I am not experienced in WebRTC and iOS and even apple devices, I am a web and low-level developer. Just was trying to make sure one of my customers can use my QR-Code scanner using his iPhone.

The weird thing for me is when I was trying Bowser on this brand-new iPad (1st gen) yesterday, everything was fine, and I was able to work with my online QR-Code scanner tool (unless some errors in rendering the page). But now after installing some random apps and enabling Siri on the iPad, the Bowser crashs!

By the way I think my customer may be still able to use Bowser on his iPhone 5 to work with my website.

**Comment by pachpage** [comment] 2015-05-21 20:09
I am using an iPhone 4S with iOS 8.3. Upon further testing, I found that if I launch Bowser from the home screen, it first says "_**Initializing:** Please wait..._" After that dialog fades, it starts to load the previously opened page (in my case, [http://www.openwebrtc.io](http://www.openwebrtc.io])). Almost immediately, the app crashes. However, if after the dialog disappears I start repeatedly pressing the reload button, it alerts me with" _**Bowser has a problem:** The operation couldn't be completed. (WebKitErrorDomain error 101.)_" When I click close, the app works fine.

Using the "bowser://" URL scheme still doesn't work, though.
![img_0758](https://cloud.githubusercontent.com/assets/11856776/7757755/9dec8abe-ffd2-11e4-986b-d445fd40d146.PNG)

**Comment by mostafar** [comment] 2015-05-21 21:19
Oh, I just found out the new version 0.5 is released today! So it answers my question why it was working yesterday, maybe I need to find a way to install version 0.4!

**Comment by iachimoe** [comment] 2015-05-21 21:21
I'm also having this problem on 3rd generation iPad. Would appreciate a fix!

**Comment by mostafar** [comment] 2015-05-21 21:23
I just received a feedback from my customer, he tested Bowser on three different iPhones (5 and 5s), and has the same problem.

**Comment by superdump** [comment] 2015-05-21 21:41
We will investigate tomorrow.

**Comment by superdump** [comment] 2015-05-22 09:08
We have managed to reproduce all of the above on an iPad 2. We will investigate further as soon as we can.

**Comment by superdump** [comment] 2015-05-25 06:51
I have identified the issue as likely being a problem with armv7 libffi. armv7s and arm64 seem to work fine.

https://gist.github.com/superdump/996d8550beaf491c99e3

Tracking it in the main OpenWebRTC repository here: https://github.com/EricssonResearch/openwebrtc/issues/385

**Comment by ekoome** [comment] 2015-05-25 15:38
Getting a crash on iPhone 5. Takes a while to initialise. When done, when I click the address bar, it crashes. On iOS 8.1.3

**Comment by unanimous1** [comment] 2015-05-27 02:24
Bowser (from App Store) crashes on iPad mini while trying to initialize.  (Running latest iOS)

**Comment by pearcetm** [comment] 2015-06-05 22:30
I'm having the the crash-after-opening problem on an iPhone 5. Downloaded today from the Apple AppStore. I just updated iOS, no fix to the problem (though the app stays open maybe 1-2 extra seconds before crashing than it did before the update).

**Comment by pearcetm** [comment] 2015-06-05 23:55
Just tried on an iPhone 5s - same problem.

**Comment by stefhak** [comment] 2015-06-06 03:35
I just tried 0.5 on my iPhone 5s, and it works FWIW.

**Comment by superdump** [comment] 2015-06-06 05:02
The 5S is ARM64 so that should be fine. I'm still trying to find libffi that builds with the current Xcode/iOS SDK and works on ARMv7/ARMv7S

**Comment by pearcetm** [comment] 2015-06-08 12:18
To follow-up from a couple of comments ago, the 5s that was having problems with Bowser had very little disk space left. After freeing up space, Bowser loads without crashing. So as others have reported, only the 5 (and presumably below) is having trouble.

**Comment by unanimous1** [comment] 2015-06-09 00:32
The iPad mini fails.   Even with disk space cleared.  It dies on boot of Bowser.

**Comment by varunFX** [comment] 2015-06-17 06:05
trying out in ipad mini, same problem here. crashes on initialization.

**Comment by superdump** [comment] 2015-06-17 06:36
I have been testing libffi versions for a few weeks that used to work on armv7 / armv7s and I have so far been unable to find anything that works anymore. I suspect something has been broken as a consequence of an Xcode upgrade.

https://github.com/EricssonResearch/openwebrtc/issues/385 <--- someone reported that they got something working there but I have been unable to get the same changes to work here.

**Comment by RichardNeill** [comment] 2015-07-10 13:32
It's failing for me on both iPad  mini and iPad 3 (updated to most recent iOS 8.4).
Is there anything I can do to help?

**Comment by superdump** [comment] 2015-07-10 14:35
I spent a few weeks trying many different libffi versions and those that supposedly worked for armv7 seemed to have stopped working or no longer built.

Libffi needs fixing so that it builds and works correctly on armv7, armv7s and arm64 for iOS

**Comment by iachimoe** [comment] 2015-08-11 19:54
Any news on this? It's starting to feel like I won't get to use WebRTC on iOS until such time as I buy a new iDevice :-)

**Comment by superdump** [comment] 2015-08-12 07:50
I need to re-test the various libffi versions with iOS SDK 8.4 to see if that helps anything.

**Comment by brentgreyling** [comment] 2015-09-04 08:14
Nice work.... Same question, any progress on this? I'm failing on Bowser 0.5 with ios 8.3 on iPhone 5.

**Comment by ageekhere** [comment] 2015-09-06 01:30
This has been one bad bug :(

**Comment by superdump** [comment] 2015-09-06 06:41
I agree and I have spent a lot of time on it already trying to find a version of libffi that builds and works on armv7 but have not yet succeeded.

It will at least get less bad with time as more people upgrade to 64-bit CPUs.

**Comment by stefanalund** [comment] 2015-09-06 08:52
I think there is an option in iOS 9 to only support 64-bit devices. Even if that leaves a lot of devices out, it is perhaps a more honest approach until we have resolved this issue.

**Comment by Firegarden** [comment] 2015-09-21 02:37
Dear God please fix this bug. We can't use bowser anymore after upgrading to ios 9.

**Comment by stefanalund** [comment] 2015-09-21 05:44
@Firegarden are you sure this is the same issue? I can start Bowser on my iPhone 5s (64-bit device) running iOS 9. Please file a separate Issue on iOS 9 compatibility otherwise.

**Comment by Firegarden** [comment] 2015-09-25 08:03
OK absolutely iPad Air 2 16GB does not work after upgrading to ios 9.-1

so there you have it I need to open a ticket but Im 2 busy coding 4 life
feel me. Tupac is 4 real.

On Sun, Sep 20, 2015 at 7:44 PM, Stefan Ålund <notifications@github.com>
wrote:

> @Firegarden <https://github.com/Firegarden> are you sure this is the same
> issue? I can start Bowser on my iPhone 5s (64-bit device) running iOS 9.
> Please file a separate Issue on iOS 9 compatibility otherwise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/bowser/issues/45#issuecomment-141881513>
> .
>



-- 
FIREGARDEN <https://www.google.com/?q=firegarden>
1877.222.7818

**Comment by stefanalund** [comment] 2015-11-14 18:28
This has been fixed in a updated version of OpenWebRTC. Let us know if you still have problems after re-building latest OpenWebRTC from master. Closing.

**Closed by stefanalund** 2015-11-14 18:28 UTC

**Comment by abhijitmehta** [comment] 2016-11-17 11:35
I get crash in iphone 6 ios 10 - is this known issue ?
